packages:
  - packages/*

catalogs:
  backend:
    '@colyseus/schema': ^2.0.25
    '@fastify/cors': ^10.0.1
    '@fastify/redis': ^6.1.0
    '@prisma/client': ^5.22.0
    colyseus: ^0.15.8
    colyseus.js: ^0.15.15
    fastify: ^5.1.0
    ioredis: ^5.4.1
    ioredis-mock: ^5.7.0
    jsonwebtoken: ^9.0.2
    lucia: ^3.2.2
    pino: ^9.3.2
    prisma: ^5.22.0
    tsx: ^4.19.0
  build:
    '@intlify/unplugin-vue-i18n': ^6.0.8
    '@shikijs/markdown-it': ^3.8.1
    '@types/howler': ^2.2.12
    '@unocss/eslint-config': ^66.3.3
    '@vite-pwa/assets-generator': ^1.0.0
    '@vitejs/plugin-vue': ^6.0.0
    beasties: ^0.3.5
    markdown-it-link-attributes: ^4.0.1
    rollup: ^4.45.1
    shiki: ^3.8.1
    unocss: ^66.3.3
    unplugin: ^2.3.5
    unplugin-auto-import: ^19.3.0
    unplugin-vue-components: ^28.8.0
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-markdown: ^29.1.0
    unplugin-vue-router: ^0.14.0
    vite: ^7.0.5
    vite-bundle-visualizer: ^1.2.1
    vite-plugin-inspect: ^11.3.0
    vite-plugin-pwa: ^1.0.1
    vite-plugin-vue-devtools: ^7.7.7
    vite-plugin-vue-layouts: ^0.11.0
    vite-ssg: ^28.0.0
    vite-ssg-sitemap: ^0.10.0
  client:
    '@radix-ui/react-progress': ^1.1.0
    '@react-three/fiber': ^8.15.0
    '@testing-library/jest-dom': ^6.6.3
    '@testing-library/react': ^16.0.0
    '@types/node': ^20.12.7
    '@types/react': ^18.2.46
    '@types/react-dom': ^18.2.18
    autoprefixer: ^10.4.18
    mock-socket: ^9.1.3
    next: ^14.2.3
    postcss: ^8.4.33
    react: ^18.2.0
    react-dom: ^18.2.0
    tailwindcss: ^3.4.4
    three: ^0.160.0
    zustand: ^4.5.2
  dev:
    '@antfu/eslint-config': ^4.17.0
    '@iconify-json/carbon': ^1.2.11
    '@iconify-json/game-icons': ^1.2.3
    '@iconify-json/iconoir': ^1.2.7
    '@iconify-json/mdi': ^1.2.3
    '@vue-macros/volar': ^3.0.0-beta.17
    '@vue/test-utils': ^2.4.6
    cypress: ^14.5.2
    cypress-vite: ^1.6.0
    eslint: ^9.31.0
    eslint-plugin-cypress: ^5.1.0
    eslint-plugin-format: ^1.0.1
    https-localhost: ^4.7.1
    lint-staged: ^16.1.2
    simple-git-hooks: ^2.13.0
    taze: ^19.1.0
    typescript: ^5.8.3
    vitest: ^3.2.4
    vue-tsc: ^3.0.3
    yaml: ^2.8.0
  frontend:
    '@headlessui/vue': ^1.7.23
    '@unhead/vue': ^2.0.12
    '@unocss/reset': ^66.3.3
    '@vueuse/core': ^13.5.0
    bitecs: ^0.3.40
    crypto-js: ^4.2.0
    floating-vue: ^5.2.2
    howler: ^2.2.4
    leaflet: ^2.0.0-alpha
    lz-string: ^1.5.0
    nprogress: ^0.2.0
    pinia: ^3.0.3
    pinia-plugin-persistedstate: ^4.4.1
    vue: ^3.5.17
    vue-i18n: ^11.1.10
    vue-number-animation: ^2.0.2
    vue-router: ^4.5.1
    vue3-select-component: ^0.11.8
    vue3-toastify: ^0.2.8
  types:
    '@types/crypto-js': ^4.2.2
    '@types/leaflet': ^1.9.20
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/nprogress': ^0.2.3
ignoredBuiltDependencies:
  - vue-demi

onlyBuiltDependencies:
  - cypress
  - esbuild
  - simple-git-hooks
