import { defineStore } from 'pinia'

export const useSaveStore = defineStore('save', () => {
  const dex = useShlagedexStore()
  const gameState = useGameStateStore()
  const game = useGameStore()
  const battleStats = useBattleStatsStore()
  const inventory = useInventoryStore()
  const dialog = useDialogStore()
  const disease = useDiseaseStore()
  const zone = useZoneStore()
  const zoneProgress = useZoneProgressStore()
  const zoneVisit = useZoneVisitStore()
  const achievements = useAchievementsStore()
  const achievementsFilter = useAchievementsFilterStore()
  const ball = useBallStore()
  const dexFilter = useDexFilterStore()
  const mainPanel = useMainPanelStore()
  const player = usePlayerStore()
  const itemUsage = useItemUsageStore()
  const equipment = useEquipmentStore()

  function reset() {
    dex.reset()
    gameState.reset()
    game.reset()
    dialog.reset()
    disease.reset()
    inventory.reset()
    zone.reset()
    zoneVisit.reset()
    zoneProgress.reset()
    achievements.reset()
    achievementsFilter.reset()
    battleStats.reset()
    ball.reset()
    dexFilter.reset()
    mainPanel.reset()
    player.reset()
    itemUsage.reset()
    equipment.reset()
  }

  return { reset }
})
