/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActiveShlagemon: typeof import('./components/panels/ActiveShlagemon.vue')['default']
    AnotherShlagemonDialog: typeof import('./components/dialog/AnotherShlagemonDialog.vue')['default']
    BattleMain: typeof import('./components/battle/BattleMain.vue')['default']
    Button: typeof import('./components/ui/Button.vue')['default']
    CheckBox: typeof import('./components/ui/CheckBox.vue')['default']
    DialogBox: typeof import('./components/dialog/DialogBox.vue')['default']
    DialogPanel: typeof import('./components/panels/DialogPanel.vue')['default']
    DialogStarter: typeof import('./components/dialog/DialogStarter.vue')['default']
    GameGrid: typeof import('./components/layout/GameGrid.vue')['default']
    Header: typeof import('./components/layout/Header.vue')['default']
    ImageByBackground: typeof import('./components/ui/ImageByBackground.vue')['default']
    InventoryItemCard: typeof import('./components/inventory/InventoryItemCard.vue')['default']
    InventoryPanel: typeof import('./components/panels/InventoryPanel.vue')['default']
    ItemCard: typeof import('./components/shop/ItemCard.vue')['default']
    Modal: typeof import('./components/modal/Modal.vue')['default']
    PanelWrapper: typeof import('./components/ui/PanelWrapper.vue')['default']
    PlayerInfos: typeof import('./components/panels/PlayerInfos.vue')['default']
    ProgressBar: typeof import('./components/ui/ProgressBar.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectedShlagemon: typeof import('./components/panels/SelectedShlagemon.vue')['default']
    Shlagedex: typeof import('./components/shlagemon/Shlagedex.vue')['default']
    ShlagemonDetail: typeof import('./components/shlagemon/ShlagemonDetail.vue')['default']
    ShlagemonRarity: typeof import('./components/shlagemon/ShlagemonRarity.vue')['default']
    ShlagemonType: typeof import('./components/shlagemon/ShlagemonType.vue')['default']
    ShopPanel: typeof import('./components/panels/ShopPanel.vue')['default']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
    TrainerBattle: typeof import('./components/battle/TrainerBattle.vue')['default']
    ZonePanel: typeof import('./components/panels/ZonePanel.vue')['default']
  }
}
