/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActiveShlagemon: typeof import('./components/panels/ActiveShlagemon.vue')['default']
    BattleMain: typeof import('./components/battle/BattleMain.vue')['default']
    CheckBox: typeof import('./components/ui/CheckBox.vue')['default']
    DialogBox: typeof import('./components/dialog/DialogBox.vue')['default']
    GameGrid: typeof import('./components/layout/GameGrid.vue')['default']
    Header: typeof import('./components/layout/Header.vue')['default']
    Modal: typeof import('./components/modal/Modal.vue')['default']
    PlayerInfos: typeof import('./components/panels/PlayerInfos.vue')['default']
    ProgressBar: typeof import('./components/ui/ProgressBar.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectedShlagemon: typeof import('./components/panels/SelectedShlagemon.vue')['default']
    Shlagedex: typeof import('./components/shlagemon/Shlagedex.vue')['default']
    ShlagemonDetail: typeof import('./components/shlagemon/ShlagemonDetail.vue')['default']
    ShlagemonType: typeof import('./components/shlagemon/ShlagemonType.vue')['default']
    StarterPanel: typeof import('./components/panels/StarterPanel.vue')['default']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
  }
}
