fr:
  title: Paramètres
  tabs:
    save: Sauvegarde
    language: Langue
    shortcuts: Raccourcis
    interface: Interface
    support: Soutien
en:
  title: Settings
  tabs:
    save: Save
    language: Language
    shortcuts: Shortcuts
    interface: Interface
    support: Support
